name: Auto Upload from Google Colab

on:
  workflow_dispatch:  # Allows manual trigger only (One-time use)

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install gdown

    - name: Download Data from Google Drive
      run: |
        gdown --folder "https://drive.google.com/drive/folders/1k161D-rqnILNj1nJSYK3DZNFPk4y9_V5?usp=drive_link" -O images/

    - name: Debug - List Files Before Commit
      run: |
        ls -R  
    
    - name: Commit and Push Changes with Custom Date
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        DATE="2023-07-15"  # Manually set the date
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add images/ *.ipynb  # Ensure notebook also gets committed
        git commit -m "📦 Auto-Uploaded on $DATE" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/Arshiyan-Elahi/Waiter-Tips-Prediction.git main
